### ISSUE TITLE
Support Ingress with wildcard hostname

### ISSUE THREAD

**Issue by bszeti** [openshift/openshift-controller-manager#190]
The Ingress resource supports host with wildcard "*", for example `*.myapps.mycompany.com`. See `host` for `.spec.rules` https://docs.openshift.com/container-platform/4.7/rest_api/network_apis/ingress-networking-k8s-io-v1.html#specification 

Currently no matching Route is created for the Ingress, even if wildcard Routes are [enabled in OpenShift.](https://docs.openshift.com/container-platform/4.7/networking/ingress-operator.html#using-wildcard-routes_configuring-ingress)

Example Ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingresswildcard
  namespace: mynamespace
spec:
  rules:
    - host: "*.myapps.mycompany.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myhello
                port: 
                  number: 8080
```

Expected Route to be created with `wildcardPolicy: Subdomain`:
```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "myingresswildcard-abc123"
  namespace: "mynamespace"
spec:
  host: "wildcard.myapps.mycompany.com"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: "myhello"
    weight: 100
  wildcardPolicy: Subdomain
```

Currently no special route with `wildcardPolicy: Subdomain` is created. The controller tries to create a regular Route with the original host from the Ingress, what causes a validation error:
```
ingress.go:342] Error syncing {bszeti myingresswildcard}: Route.route.openshift.io "myingresswildcard-r5w6p" is invalid: spec.host: Invalid value: "*.myingress-bszetix.mycompany.com": host must conform to DNS 1123 naming conventions: [spec.host: Invalid value: "*.myingress-bszetix.mycompany.com": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
```
