### ISSUE TITLE
Enable annotations config for build controller

### ISSUE THREAD

**Issue by maratsal** [openshift/openshift-controller-manager#225]
Currently build controller supports injecting custom annotations to build pod - https://github.com/openshift/openshift-controller-manager/blob/master/pkg/build/controller/build/overrides/overrides.go#L81-L84

However annotations option is not available in CRD - https://github.com/openshift/openshift-controller-manager/blob/master/vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml

Code like this would be enough:
```
                  annotations:
                    additionalProperties:
                      type: string
                    description: 'Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations'
                    type: object
```

Are there some particular reasons annotations option was not included to the cluster config CRD for builds?
Is it possible to add that option to CRD?

We have got an issue with one of the applications deployment that was injecting side container to the pod and this is breaking the build. To exclude pods form injecting of the side container  annotation must be added to the pod.
